GET http://localhost:3001/api/notes

###

DELETE http://localhost:3001/api/notes/675a158dd4af5592b8d2ac19

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "New note from requests.rest",
    "important": true
}

###